# Generated by Django 3.1 on 2022-04-26 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
